Text file Task1 is added.
ViktoriaBilevich/Lesson1 pull request #1
Opened 2021-01-29 21:27 UTC by ViktoriaBilevich

The "Task1" file contains homework for the lesson1.

2021-02-01 22:30 UTC, AntonShtabnoy requested changes

2021-02-01 22:30 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson1/HomeTask1.java
> +        int sot = (n%1000-des)/100;
Обрати внимание на форматирование ( n % 100 - ed ) / 10 - везде должны быть пробелы между символами. Автоформатирование делается сочетанием клавиш ctrl+alt+L

2021-02-01 22:30 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson1/HomeTask1.java
> +        if(ed != des && ed != sot && ed != tis && des!=sot && des != tis && sot !=tis) {
Задание можно решить через 3 условия - по возможности подумать

2021-02-01 22:30 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson1/HomeTask1.java
> +        int chetn = ed%2;
Потренироваться над названиями переменных - не все понятно с первого прочтения

2021-02-01 22:31 UTC, AntonShtabnoy requested changes

2021-02-01 22:31 UTC, AntonShtabnoy commented on src/Main.java
> +import com.javacourse.se.lesson1.HomeTask1;
Ко второму заданию: Команда в консоли должна выглядеть java -cp /home Main Privet
И вот эту строку(Privet) что я передаю в конце должна вывести программа на экран

2021-02-02 08:43 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson1/HomeTask1.java
> +        if(ed != des && ed != sot && ed != tis && des!=sot && des != tis && sot !=tis) {
Не знаю, как прописать три условия. Если три условия, то я так понимаю сравниваются только единицы с десятками, десятки с сотнями, сотни с тысячами. Но десятки могут быть равны тысячам и т.д. Если будет возможность расскажите правильное решение

2021-02-02 08:44 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson1/HomeTask1.java
> +        int chetn = ed%2;
Fixed

2021-02-02 08:44 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson1/HomeTask1.java
> +        int sot = (n%1000-des)/100;
Fixed

2021-02-02 08:44 UTC, ViktoriaBilevich commented on src/Main.java
> +import com.javacourse.se.lesson1.HomeTask1;
Fixed

2021-02-07 23:55 UTC, merged