Methods "reverseNumber", "compareNumber" were updated
ViktoriaBilevich/Lesson1 pull request #2
Opened 2021-02-03 20:32 UTC by ViktoriaBilevich

Methods "reverseNumber", "compareNumber" were updated

2021-02-07 23:57 UTC, AntonShtabnoy requested changes

2021-02-07 23:57 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson2/HomeTask2.java
> +        int result = array[0] * 1000 + array[1] * 100 + array[2] * 10 + array[3];
А если будет 5 число? или 7 значное? - твое решение сломается

2021-02-07 23:57 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson2/HomeTask2.java
> +            System.out.println("Все цифры числа различны");
Аналогично первому - нужно написать алгоритм который будет работать для всех входных данных

2021-02-08 19:32 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson2/HomeTask2.java
> +        int result = array[0] * 1000 + array[1] * 100 + array[2] * 10 + array[3];
исправила

2021-02-08 19:32 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson2/HomeTask2.java
> +            System.out.println("Все цифры числа различны");
исправила

2021-02-14 21:39 UTC, AntonShtabnoy approved these changes

2021-02-20 12:42 UTC, merged