add HomeTask5
ViktoriaBilevich/Lesson1 pull request #5
Opened 2021-02-14 18:52 UTC by ViktoriaBilevich

add HomeTask5

2021-02-14 21:48 UTC, AntonShtabnoy requested changes

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/Book.java
> +    String author;
В задании написано автор(ы) сл-но может быть несколько - надо менять тип поля

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/BookService.java
> +        }
Метод должен возвращать массив найденных книг - чтобы я мог дальше с ними работать

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/BookService.java
> +        }
Практика названия метод, поиск одного find(), по какому-то параметру findByParam(), для мно-ва числа findAll()

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/Customer.java
> +    long bankAccountNumber;
в банковском счете могут быть буквы

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/CustomerService.java
> +public class CustomerService {
весь вывод должен происходить в demo классе, зднсь только изменяем, ищем и возвращаем результат, чт с ним дальше работать в демо классе

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/TimePeriod.java
> +    public void Print() {
методы называются с маленькой буквы

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/Fraction.java
> +        this.n = n;
Знаменатель может быть равен 0? - по сути объект вообще не должен создаваться

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/FractionService.java
> +public class FractionService {
Для более лучшего решения - лучше реализовать метод сокращение дробей  и после каждого действия сокращать дробь

2021-02-14 21:48 UTC, AntonShtabnoy commented on src/com/javacourse/se/lesson5/Book.java
> +package com.javacourse.se.lesson5;
Молодец! Очень понравилось как сделала данное дз!

2021-02-17 20:10 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/Book.java
> +    String author;
исправила

2021-02-17 20:10 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/BookService.java
> +        }
исправила

2021-02-17 20:10 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/Customer.java
> +    long bankAccountNumber;
исправила

2021-02-17 20:10 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/CustomerService.java
> +public class CustomerService {
исправила

2021-02-17 20:10 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/TimePeriod.java
> +    public void Print() {
исправила

2021-02-17 20:10 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/Fraction.java
> +        this.n = n;
исправила

2021-02-17 20:11 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/FractionService.java
> +public class FractionService {
исправила

2021-02-17 20:11 UTC, ViktoriaBilevich commented on src/com/javacourse/se/lesson5/Book.java
> +package com.javacourse.se.lesson5;
Спасибо

2021-02-23 13:24 UTC, merged